In [1]:
import pandas as pd
import numpy as np

In [4]:
file_path = "Predict_data.xlsx"
Data_df = pd.read_excel(file_path, sheet_name=0,header=0)
Feature_df = pd.read_excel(file_path, sheet_name=1, header=0,index_col=0)

In [5]:
Data_df

,d33,Tc,Pb-2,Ti-4,Bi-3,Sc-3,Ni-2,Zr-4,Mn-2,Zn-2,...,In-3,Nb-5,Sn-2,Cd-2,Sb-5,Mg-2,Li-1,Sb-3,Mn-3,W-6
0,0,0,0.64,0.6336,0.36,0.36,0.00032,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.000320
1,0,0,0.64,0.6272,0.36,0.36,0.00064,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.000640
2,0,0,0.64,0.6208,0.36,0.36,0.00096,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.000960
3,0,0,0.64,0.6144,0.36,0.36,0.00128,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.001280
4,0,0,0.64,0.6336,0.36,0.36,0.00000,0,0.00032,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.000320
5,0,0,0.64,0.6272,0.36,0.36,0.00000,0,0.00064,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.000640
6,0,0,0.64,0.6208,0.36,0.36,0.00000,0,0.00096,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.000960
7,0,0,0.64,0.6144,0.36,0.36,0.00000,0,0.00128,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.001280
8,0,0,0.64,0.6336,0.36,0.36,0.00000,0,0.00000,0.00032,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.000320
9,0,0,0.64,0.6272,0.36,0.36,0.00000,0,0.00000,0.00064,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.000640
10,0,0,0.64,0.6208,0.36,0.36,0.00000,0,0.00000,0.00096,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.000960
11,0,0,0.64,0.6144,0.36,0.36,0.00000,0,0.00000,0.00128,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.001280
12,0,0,0.64,0.6336,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00032,0,0,0,0.000320
13,0,0,0.64,0.6272,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00064,0,0,0,0.000640
14,0,0,0.64,0.6208,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00096,0,0,0,0.000960
15,0,0,0.64,0.6144,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00128,0,0,0,0.001280
16,0,0,0.64,0.6336,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00032,0,0.00000,0,0,0,0.000320
17,0,0,0.64,0.6272,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00064,0,0.00000,0,0,0,0.000640
18,0,0,0.64,0.6208,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00096,0,0.00000,0,0,0,0.000960
19,0,0,0.64,0.6144,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00128,0,0.00000,0,0,0,0.001280
20,0,0,0.64,0.6336,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.002133
21,0,0,0.64,0.6272,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.004267
22,0,0,0.64,0.6208,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.006400
23,0,0,0.64,0.6144,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.008533
24,0,0,0.64,0.6336,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.002133
25,0,0,0.64,0.6272,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.004267
26,0,0,0.64,0.6208,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.006400
27,0,0,0.64,0.6144,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.000000,0,0,0.00000,0,0.00000,0,0,0,0.008533
28,0,0,0.64,0.6336,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.004267,0,0,0.00000,0,0.00000,0,0,0,0.002133
29,0,0,0.64,0.6272,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.008533,0,0,0.00000,0,0.00000,0,0,0,0.004267
30,0,0,0.64,0.6208,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.012800,0,0,0.00000,0,0.00000,0,0,0,0.006400
31,0,0,0.64,0.6144,0.36,0.36,0.00000,0,0.00000,0.00000,...,0.017067,0,0,0.00000,0,0.00000,0,0,0,0.008533

In [6]:
Feature_df

,Pb-2,Ti-4,Bi-3,Sc-3,Ni-2,Zr-4,Mn-2,Mn-3,Zn-2,Yb-3,Ga-3,In-3,Nb-5,Sn-2,Cd-2,Sb-3,Sb-5,Mg-2,Li-1,W-6
position,A,B,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,B
RSC6,119,60.5,103,74.5,69,72,83,64.5,74,86.8,62,80,64,118,95,76,60,72,76,60
RSC12,149,0,138.01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,115.93,0
RC,154,132,152,144,115,145,117,117,125,170,125,150,134,140,141,141,141,136,123,130
RP,2.09,2.58,1.997,2.75,2.18,2.825,2.22,2.22,1.88,3.59,1.695,2.05,2.76,1.88,2.215,1.765,1.765,2.03,1.61,2.735
Rdce,1.43,0.91,1.38,1.1,1.13,0.98,0.79,0.79,1.25,1,1.38,1.49,0.95,1.41,1.39,1.32,1.32,1.09,1.75,0.92
Rdve,2.32,1.81,2.25,2.21,2.9,1.96,1.26,1.26,2.21,1.99,2,2.3,1.75,2.3,2.4,2.15,2.15,2.3,3.06,1.5
Ven,4,4,5,3,10,4,7,7,12,16,3,3,5,4,12,5,5,2,1,6
Ne/IR,0.536913,0.297521,0.579668,0.241611,0.376812,0.5,0.277108,0.341085,0.378378,0.771889,0.451613,0.575,0.5625,0.40678,0.484211,0.631579,0.766667,0.138889,0.017252,1.133333
CNE_C/IR,0.082483,0.079669,0.09666,0.062148,0.082754,0.089583,0.063012,0.081085,0.080676,0.098963,0.100323,0.105875,0.104688,0.077119,0.086211,0.131447,0.1665,0.045972,0.011041,0.164167
CNE_S/IR,0.037517,0.052066,0.045649,0.040268,0.058696,0.041667,0.043373,0.055814,0.058784,0.032834,0.080645,0.0625,0.051562,0.047881,0.045789,0.082895,0.105,0.039583,0.011214,0.0725
VEC_Z,0.04878,0.181818,0.060241,0.142857,0.357143,0.1,0.28,0.28,0.4,0.228571,0.096774,0.061224,0.121951,0.08,0.25,0.098039,0.098039,0.166667,0.333333,0.081081
Val_IR,0.013423,0.066116,0.021738,0.040268,0.028986,0.055556,0.024096,0.046512,0.027027,0.034562,0.048387,0.0375,0.078125,0.016949,0.021053,0.039474,0.083333,0.027778,0.008626,0.1
CNE_C,12.29,4.82,13.34,4.63,5.71,6.45,5.23,5.23,5.97,8.59,6.22,8.47,6.7,9.1,8.19,9.99,9.99,3.31,1.28,9.85
CNE_S,5.59,3.15,6.3,3,4.05,3,3.6,3.6,4.35,2.85,5,5,3.3,5.65,4.35,6.3,6.3,2.85,1.3,4.35
CP,4.1,3.8,4.15,3.25,5.2,3.45,4.45,4.45,4.1,3.22,4.1,3.9,4.05,4.15,4.05,4.4,4.4,3.45,2.85,4.8
Valence,2,4,3,3,2,4,2,3,2,3,3,3,5,2,2,3,5,2,1,6
AN,82,22,83,21,28,40,25,25,30,70,31,49,41,50,48,51,51,12,3,74
AW,207.2,47.867,208.9804,44.9559,58.6934,91.224,54.938,54.938,65.38,173.04,69.723,114.818,92.906,118.71,112.414,121.76,121.76,24.305,6.94,183.85
AV,3.034,1.764,3.538,2.5,1.093,2.328,1.22,1.22,1.521,4.128,1.947,2.617,1.807,2.705,2.144,2.997,2.997,2.324,2.162,1.586
AR,154,176,143,184,149,206,161,161,142,222,136,156,198,145,161,133,133,145,167,135
IP,2,0.185,1.74,0.286,0.386,0.37,0.527,0.329,0.288,0.689,0.198,0.73,0.261,0.499,1.09,0.927,0.36,0.094,0.029,0.181
Electrons,80,18,80,18,26,36,23,22,28,67,28,46,36,48,46,48,46,10,2,68
EN-A,1.55,1.32,1.55,1.2,1.75,1.22,1.6,1.6,1.66,1.06,1.82,1.49,1.23,1.72,1.46,1.82,1.82,1.23,0.97,1.4
EN_MB,1.92,1.86,1.92,1.5,1.76,1.7,2.04,2.04,1.44,1.1,1.7,1.63,2.03,1.88,1.4,2.14,2.14,1.31,0.9,1.79
EN-P,1.9,1.5,1.9,1.3,1.9,1.4,1.5,1.5,1.6,1.05,1.6,1.7,1.6,1.8,1.7,1.9,1.9,1.2,1,1.7
EA,35.1,7.6,91.3,18.1,156,41.1,0,0,9,50,30,30,86.2,116,-26,101,101,-21,59.6,78.6
Period,6,4,6,4,4,5,4,4,4,6,4,5,5,5,5,5,5,3,2,6
RVdw,254,246,280,258,240,252,245,245,239,274,232,243,256,242,249,247,247,251,212,249
I1,715.6,658,703.3,631,736.7,660,717.4,717.4,906.4,603.4,578.8,558.3,663.8,708.6,867.7,833.7,833.7,737.7,520.2,770
I2,1450.42,1310,1610,1235,1753,1267,1509,1509,1733,1174,1979,1821,1382,1412,1631,1595,1595,1451,7298,1708
I3,3081.48,2653,2466,2389,3393,2218,3248,3248,3833,2408,2963,2705,2416,2943,3616,2441,2441,7733,11815,2316
OF,0.85,0.432143,0.735714,0.532143,0.492857,0.514286,0.592857,0.460714,0.528571,0.62,0.442857,0.571429,0.457143,0.842857,0.678571,0.542857,0.428571,0.514286,0.542857,0.428571

In [7]:
def calculate_weighted_average(properties_df, probabilities_df, position):
    """
    计算各种性质的加权平均数。
    """
    # 过滤出所需位置（A或B）的元素
    elements = properties_df.columns[properties_df.loc['position'] == position]
    
    # 筛选出这些元素的概率
    probabilities = probabilities_df[elements]
    
    # 计算加权平均数
    weighted_averages = {}
    for property_name in properties_df.index:
        if property_name == 'position':
            continue  # 跳过位置行
        weighted_averages[property_name + '_' +position] = (
            properties_df.loc[property_name, elements] * probabilities
        ).sum(axis=1) / probabilities.sum(axis=1)
    
    # 将结果转换为DataFrame
    weighted_averages_df = pd.DataFrame(weighted_averages)
    
    return weighted_averages_df

def calc_tolerance_factor(r_A, r_B, r_X=140):
    """
    计算容忍因子。
    """
    t = (r_A + r_X) / (1.414 * (r_B + r_X))
    return t

In [8]:
weighted_averages_df_A = calculate_weighted_average(Feature_df,Data_df,'A').drop(columns='RSC6_A')
weighted_averages_df_B = calculate_weighted_average(Feature_df,Data_df,'B').drop(columns='RSC12_B')

tolerance_factor = pd.DataFrame(calc_tolerance_factor(weighted_averages_df_A['RSC12_A'], weighted_averages_df_B['RSC6_B']),columns=['t'])

Feature_combined_df = pd.concat([Data_df.iloc[:,:2],weighted_averages_df_A,weighted_averages_df_B,tolerance_factor],axis=1)

In [9]:
Feature_combined_df #examination

,d33,Tc,RSC12_A,RC_A,RP_A,Rdce_A,Rdve_A,Ven_A,Ne/IR_A,CNE_C/IR_A,...,EN_MB_B,EN-P_B,EA_B,Period_B,RVdw_B,I1_B,I2_B,I3_B,OF_B,t
0,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.729594,1.427776,11.472514,4.000644,250.344062,648.285066,1283.114258,2557.539105,0.46837,0.980615
1,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.72878,1.427549,11.566106,4.001295,250.368404,648.290191,1283.229848,2557.113305,0.468599,0.980461
2,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.727955,1.42732,11.660795,4.001954,250.393032,648.295376,1283.346793,2556.682514,0.468832,0.980306
3,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.727121,1.427088,11.7566,4.00262,250.41795,648.300622,1283.465116,2556.246643,0.469067,0.98015
4,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.729685,1.427647,11.422304,4.000644,250.345671,648.278854,1283.035726,2557.492436,0.468402,0.980593
5,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.728961,1.42729,11.465102,4.001295,250.371641,648.277695,1283.071868,2557.019424,0.468664,0.980418
6,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.728229,1.426929,11.508401,4.001954,250.397916,648.276522,1283.108434,2556.540866,0.468929,0.980241
7,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.727488,1.426564,11.552211,4.00262,250.4245,648.275336,1283.145431,2556.056666,0.469198,0.980062
8,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.729491,1.427679,11.425201,4.000644,250.34374,648.339685,1283.107821,2557.680721,0.468381,0.980607
9,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.728572,1.427355,11.470929,4.001295,250.367757,648.400065,1283.216899,2557.398187,0.468623,0.980446
10,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.727642,1.427027,11.517193,4.001954,250.392055,648.461153,1283.327255,2557.112341,0.468867,0.980283
11,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.726702,1.426695,11.564003,4.00262,250.416639,648.522961,1283.438913,2556.823125,0.469114,0.980118
12,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.72945,1.427551,11.415546,4.000322,250.347602,648.285388,1283.017058,2558.935951,0.468377,0.98061
13,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.728488,1.427096,11.451505,4.000647,250.375526,648.290838,1283.034315,2559.923276,0.468613,0.980452
14,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.727515,1.426636,11.487887,4.000977,250.403777,648.296353,1283.051775,2560.922175,0.468853,0.980292
15,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.726531,1.426171,11.524697,4.00131,250.432362,648.301933,1283.06944,2561.932853,0.469095,0.980131
16,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.729479,1.427712,11.413936,4.000966,250.346958,648.327229,1283.074992,2557.610879,0.46843,0.980575
17,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.728546,1.42742,11.448268,4.001942,250.374231,648.375008,1283.150858,2557.257689,0.46872,0.980381
18,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.727603,1.427125,11.483002,4.002931,250.401824,648.423347,1283.227613,2556.900358,0.469013,0.980185
19,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.726649,1.426826,11.518146,4.003931,250.429741,648.472257,1283.305274,2556.538814,0.46931,0.979987
20,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.727008,1.426507,11.712373,4.0128,250.445867,648.285973,1283.2688,2556.195733,0.468937,0.980236
21,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.723616,1.425013,12.044747,4.0256,250.571733,648.291947,1283.5376,2554.431467,0.469731,0.979707
22,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.720224,1.42352,12.37712,4.0384,250.6976,648.29792,1283.8064,2552.6672,0.470525,0.979178
23,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.716832,1.422027,12.709493,4.0512,250.823467,648.303893,1284.0752,2550.902933,0.471318,0.978649
24,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.729568,1.428853,11.62704,4.004267,250.266667,648.181013,1286.703467,2558.563733,0.468181,0.980741
25,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.728736,1.429707,11.87408,4.008533,250.213333,648.082027,1290.406933,2559.167467,0.468219,0.980715
26,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.727904,1.43056,12.12112,4.0128,250.16,647.98304,1294.1104,2559.7712,0.468257,0.98069
27,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.727072,1.431413,12.36816,4.017067,250.106667,647.884053,1297.813867,2560.374933,0.468295,0.980665
28,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.729269,1.42928,11.62704,4.008533,250.3136,648.093547,1286.029333,2557.462933,0.46873,0.980375
29,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.728139,1.43056,11.87408,4.017067,250.3072,647.907093,1289.058667,2556.965867,0.469316,0.979983
30,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.727008,1.43184,12.12112,4.0256,250.3008,647.72064,1292.088,2556.4688,0.469903,0.979592
31,0,0,145.0436,153.28,2.05652,1.412,2.2948,4.36,0.552305,0.087587,...,1.725877,1.43312,12.36816,4.034133,250.2944,647.534187,1295.117333,2555.971733,0.47049,0.979201

In [10]:
file_path = "Feature_selected.xlsx"
Feature_group_df = pd.read_excel(file_path, header=0)

In [11]:
features = Feature_group_df["Feature"].tolist()

In [12]:
selected_Feature = pd.concat([Feature_combined_df.iloc[:,:2],Feature_combined_df[Feature_combined_df.columns.intersection(features)]],axis=1)

In [26]:
selected_Feature.to_excel("pre_data.xlsx")

In [16]:
import joblib
from sklearn.preprocessing import StandardScaler

best_model_d = joblib.load('best_xgb_model.pkl')
best_model_t = joblib.load('best_BR_model.pkl')
scaler = joblib.load('scaler_X.pkl')

In [19]:
selected_Feature.iloc[:,2:]

,RSC12_A,RC_A,Ne/IR_A,EA_A,RVdw_A,RSC6_B,RC_B,RP_B,Rdce_B,Rdve_B,...,CNE_S_B,IP_B,Electrons_B,EN-A_B,EN_MB_B,EN-P_B,EA_B,I1_B,I3_B,t
0,145.0436,153.28,0.552305,55.332,263.36,65.571773,136.338912,2.641476,0.97887,1.955085,...,3.096363,0.221634,18.018668,1.276714,1.729594,1.427776,11.472514,648.285066,2557.539105,0.980615
1,145.0436,153.28,0.552305,55.332,263.36,65.603917,136.358045,2.641755,0.979346,1.956183,...,3.09673,0.221911,18.037553,1.276627,1.72878,1.427549,11.566106,648.290191,2557.113305,0.980461
2,145.0436,153.28,0.552305,55.332,263.36,65.636438,136.377401,2.642037,0.979827,1.957294,...,3.097102,0.222192,18.056659,1.276539,1.727955,1.42732,11.660795,648.295376,2556.682514,0.980306
3,145.0436,153.28,0.552305,55.332,263.36,65.669342,136.396987,2.642322,0.980314,1.958418,...,3.097478,0.222476,18.075991,1.276449,1.727121,1.427088,11.7566,648.300622,2556.246643,0.98015
4,145.0436,153.28,0.552305,55.332,263.36,65.576279,136.339556,2.641489,0.978761,1.954557,...,3.096218,0.221679,18.017702,1.276666,1.729685,1.427647,11.422304,648.278854,2557.492436,0.980593
5,145.0436,153.28,0.552305,55.332,263.36,65.612982,136.35934,2.641781,0.979126,1.955121,...,3.096439,0.222003,18.03561,1.27653,1.728961,1.42729,11.465102,648.277695,2557.019424,0.980418
6,145.0436,153.28,0.552305,55.332,263.36,65.650114,136.379355,2.642076,0.979495,1.955692,...,3.096662,0.22233,18.053728,1.276392,1.728229,1.426929,11.508401,648.276522,2556.540866,0.980241
7,145.0436,153.28,0.552305,55.332,263.36,65.687684,136.399607,2.642375,0.979869,1.956269,...,3.096888,0.22266,18.07206,1.276253,1.727488,1.426564,11.552211,648.275336,2556.056666,0.980062
8,145.0436,153.28,0.552305,55.332,263.36,65.573383,136.342131,2.641379,0.978909,1.954863,...,3.09646,0.221603,18.019311,1.276685,1.729491,1.427679,11.425201,648.339685,2557.680721,0.980607
9,145.0436,153.28,0.552305,55.332,263.36,65.607154,136.364519,2.64156,0.979424,1.955736,...,3.096925,0.221848,18.038848,1.276568,1.728572,1.427355,11.470929,648.400065,2557.398187,0.980446
10,145.0436,153.28,0.552305,55.332,263.36,65.641322,136.38717,2.641744,0.979945,1.95662,...,3.097395,0.222096,18.058613,1.276451,1.727642,1.427027,11.517193,648.461153,2557.112341,0.980283
11,145.0436,153.28,0.552305,55.332,263.36,65.675893,136.410088,2.641929,0.980472,1.957514,...,3.097871,0.222347,18.078611,1.276331,1.726702,1.426695,11.564003,648.522961,2556.823125,0.980118
12,145.0436,153.28,0.552305,55.332,263.36,65.572739,136.345671,2.641427,0.978857,1.954892,...,3.095977,0.22154,18.013518,1.276547,1.72945,1.427551,11.415546,648.285388,2558.935951,0.98061
13,145.0436,153.28,0.552305,55.332,263.36,65.60586,136.371641,2.641657,0.97932,1.955795,...,3.095953,0.221722,18.027193,1.27629,1.728488,1.427096,11.451505,648.290838,2559.923276,0.980452
14,145.0436,153.28,0.552305,55.332,263.36,65.639368,136.397916,2.64189,0.979788,1.956708,...,3.09593,0.221907,18.041029,1.276031,1.727515,1.426636,11.487887,648.296353,2560.922175,0.980292
15,145.0436,153.28,0.552305,55.332,263.36,65.673272,136.4245,2.642126,0.980262,1.957632,...,3.095906,0.222093,18.055028,1.275768,1.726531,1.426171,11.524697,648.301933,2561.932853,0.980131
16,145.0436,153.28,0.552305,55.332,263.36,65.580142,136.34728,2.641487,0.978954,1.954924,...,3.09646,0.221861,18.025105,1.276621,1.729479,1.427712,11.413936,648.327229,2557.610879,0.980575
17,145.0436,153.28,0.552305,55.332,263.36,65.620751,136.374879,2.641777,0.979514,1.95586,...,3.096925,0.222367,18.050502,1.276439,1.728546,1.42742,11.448268,648.375008,2557.257689,0.980381
18,145.0436,153.28,0.552305,55.332,263.36,65.661837,136.4028,2.642071,0.980081,1.956806,...,3.097395,0.22288,18.076197,1.276255,1.727603,1.427125,11.483002,648.423347,2556.900358,0.980185
19,145.0436,153.28,0.552305,55.332,263.36,65.703406,136.431051,2.642368,0.980655,1.957763,...,3.097871,0.223398,18.102195,1.276069,1.726649,1.426826,11.518146,648.472257,2556.538814,0.979987
20,145.0436,153.28,0.552305,55.332,263.36,65.651147,136.477867,2.64584,0.978805,1.954107,...,3.09728,0.223502,18.315733,1.275861,1.727008,1.426507,11.712373,648.285973,2556.195733,0.980236
21,145.0436,153.28,0.552305,55.332,263.36,65.762293,136.635733,2.65048,0.979211,1.954213,...,3.09856,0.225644,18.631467,1.274923,1.723616,1.425013,12.044747,648.291947,2554.431467,0.979707
22,145.0436,153.28,0.552305,55.332,263.36,65.87344,136.7936,2.65512,0.979616,1.95432,...,3.09984,0.227786,18.9472,1.273984,1.720224,1.42352,12.37712,648.29792,2552.6672,0.979178
23,145.0436,153.28,0.552305,55.332,263.36,65.984587,136.951467,2.65976,0.980021,1.954427,...,3.10112,0.229927,19.262933,1.273045,1.716832,1.422027,12.709493,648.303893,2550.902933,0.978649
24,145.0436,153.28,0.552305,55.332,263.36,65.545333,136.285867,2.637755,0.980427,1.954149,...,3.106453,0.221407,18.149333,1.279104,1.729568,1.428853,11.62704,648.181013,2558.563733,0.980741
25,145.0436,153.28,0.552305,55.332,263.36,65.550667,136.251733,2.634309,0.982453,1.954299,...,3.116907,0.221454,18.298667,1.281408,1.728736,1.429707,11.87408,648.082027,2559.167467,0.980715
26,145.0436,153.28,0.552305,55.332,263.36,65.556,136.2176,2.630864,0.98448,1.954448,...,3.12736,0.221501,18.448,1.283712,1.727904,1.43056,12.12112,647.98304,2559.7712,0.98069
27,145.0436,153.28,0.552305,55.332,263.36,65.561333,136.183467,2.627419,0.986507,1.954597,...,3.137813,0.221548,18.597333,1.286016,1.727072,1.431413,12.36816,647.884053,2560.374933,0.980665
28,145.0436,153.28,0.552305,55.332,263.36,65.622133,136.392533,2.639269,0.980896,1.955429,...,3.106453,0.223677,18.226133,1.277696,1.729269,1.42928,11.62704,648.093547,2557.462933,0.980375
29,145.0436,153.28,0.552305,55.332,263.36,65.704267,136.465067,2.637339,0.983392,1.956859,...,3.116907,0.225994,18.452267,1.278592,1.728139,1.43056,11.87408,647.907093,2556.965867,0.979983
30,145.0436,153.28,0.552305,55.332,263.36,65.7864,136.5376,2.635408,0.985888,1.958288,...,3.12736,0.22831,18.6784,1.279488,1.727008,1.43184,12.12112,647.72064,2556.4688,0.979592
31,145.0436,153.28,0.552305,55.332,263.36,65.868533,136.610133,2.633477,0.988384,1.959717,...,3.137813,0.230627,18.904533,1.280384,1.725877,1.43312,12.36816,647.534187,2555.971733,0.979201

In [20]:
X_new_scaled = scaler.transform(selected_Feature.iloc[:,2:])

In [59]:
Predict_d = best_model_d.predict(X_new_scaled)
Predict_t = best_model_t.predict(X_new_scaled)

c:\Users\zzp\miniconda3\envs\Ceramic\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but BayesianRidge was fitted with feature names
  warnings.warn(

In [22]:
Predict_d

array([409.51978, 343.8099 , 292.9977 , 257.74942, 379.94177, 289.3931 ,
       289.60052, 256.05896, 414.59924, 359.25415, 321.47498, 311.1123 ,
       394.0511 , 382.90204, 284.40952, 272.68274, 413.05652, 310.0937 ,
       317.30133, 268.3361 , 434.73166, 430.11172, 452.3691 , 407.15714,
       374.72708, 295.23233, 347.81705, 422.19742, 313.53662, 335.339  ,
       357.09094, 376.03473], dtype=float32)

In [23]:
Predict_t

array([433.42437883, 431.62571125, 429.80607428, 427.96509901,
       433.94841076, 432.67991662, 431.39670317, 430.09851267,
       433.74386277, 432.26841422, 430.77579723, 429.26571033,
       434.31612186, 433.41959688, 432.51268507, 431.59520482,
       433.57092747, 431.92058378, 430.25107831, 428.56207528,
       434.92440238, 434.64772461, 434.37240193, 434.09843217,
       435.9193232 , 436.63621207, 437.35310407, 438.0699992 ,
       433.1069586 , 431.01222124, 428.91822448, 426.82496744])

In [75]:
new_df = pd.read_excel('newdata.xlsx', sheet_name=0, header=0)

In [76]:
new_df

,d33,Tc,RSC12_A,RC_A,Ne/IR_A,EA_A,RVdw_A,RSC6_B,RC_B,RP_B,...,CNE_S_B,IP_B,Electrons_B,EN-A_B,EN_MB_B,EN-P_B,EA_B,I1_B,I3_B,t
0,434,426,145.0436,153.28,0.552305,55.332,263.36,65.571773,136.338912,2.641476,...,3.096363,0.221634,18.018668,1.276714,1.729594,1.427776,11.472514,648.285066,2557.539105,0.980615
1,430,424,145.0436,153.28,0.552305,55.332,263.36,65.573383,136.342131,2.641379,...,3.096460,0.221603,18.019311,1.276685,1.729491,1.427679,11.425201,648.339685,2557.680721,0.980607
2,445,0,145.0436,153.28,0.552305,55.332,263.36,65.607154,136.364519,2.641560,...,3.096925,0.221848,18.038848,1.276568,1.728572,1.427355,11.470929,648.400065,2557.398187,0.980446
3,465,0,145.0436,153.28,0.552305,55.332,263.36,65.641322,136.387170,2.641744,...,3.097395,0.222096,18.058613,1.276451,1.727642,1.427027,11.517193,648.461153,2557.112341,0.980283
4,451,0,145.0436,153.28,0.552305,55.332,263.36,65.675893,136.410088,2.641929,...,3.097871,0.222347,18.078611,1.276331,1.726702,1.426695,11.564003,648.522961,2556.823125,0.980118
5,500,0,145.0436,153.28,0.552305,55.332,263.36,65.572739,136.345671,2.641427,...,3.095977,0.221540,18.013518,1.276547,1.729450,1.427551,11.415546,648.285388,2558.935951,0.980610

In [70]:
new_df.iloc[:1,2:]

,RSC12_A,RC_A,Ne/IR_A,EA_A,RVdw_A,RSC6_B,RC_B,RP_B,Rdce_B,Rdve_B,...,CNE_S_B,IP_B,Electrons_B,EN-A_B,EN_MB_B,EN-P_B,EA_B,I1_B,I3_B,t
0,145.0436,153.28,0.552305,55.332,263.36,65.571773,136.338912,2.641476,0.97887,1.955085,...,3.096363,0.221634,18.018668,1.276714,1.729594,1.427776,11.472514,648.285066,2557.539105,0.980615

In [71]:
Predict_d = best_model_d.predict(X_new_scaled)
Predict_t = best_model_t.predict(X_new_scaled)

c:\Users\zzp\miniconda3\envs\Ceramic\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but BayesianRidge was fitted with feature names
  warnings.warn(

In [ ]:

best_model_d.fit(
    new_df.iloc[:2,2:], 
    new_df.iloc[:2,:1], 
    xgb_model=best_model_d.get_booster()   # 指定继续训练
)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=np.float64(0.6588293923716152), device=None,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, feature_weights=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None,
             learning_rate=np.float64(0.1953175250322989), max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=607, n_jobs=-1,
             num_parallel_tree=None, ...)

In [78]:
 new_df.iloc[:2,1:2]

    Tc
0  426
1  424

In [ ]:

best_model_t.fit(
    new_df.iloc[:2,2:], 
    new_df.iloc[:2,1:2], 
    xgb_model=best_model_t.get_booster()   # 指定继续训练
)

AttributeError: 'BayesianRidge' object has no attribute 'get_booster'

In [73]:
Predict_d = best_model_d.predict(X_new_scaled)

In [74]:
Predict_d

array([510.0294 , 444.31958, 393.50732, 358.23233, 480.45135, 389.9027 ,
       390.11017, 356.5419 , 515.10895, 459.76373, 421.98468, 411.62213,
       494.56067, 483.41162, 384.91925, 373.16574, 513.5662 , 410.60345,
       417.81104, 368.81906, 535.2414 , 530.62146, 552.8788 , 507.6668 ,
       475.2367 , 395.74194, 448.32666, 522.70715, 414.0465 , 435.84863,
       457.6006 , 476.5443 ], dtype=float32)